title: Chauncey Robinson Portfolio
logo: "/images/1621449376476.jpg?raw=true"
description: >
  First description
  <br><br>
  Second description
linkedin: https://www.linkedin.com/in/chauncey-robinson
github: https://github.com/Chauncey-Robinson
