title: Chauncey Robinson Portfolio
logo: "/images/1621449376476.jpg?raw=true"
description: >
  Welcome to my portfolio! Here you can find some of the projects I've worked on.
linkedin: https://www.linkedin.com/in/chauncey-robinson
github: https://github.com/Chauncey-Robinson
